name: ble_plus_example_unused
description: DEPRECATED - see root example/ instead.
version: 1.0.4
repository: https://github.com/ajinkya446/ble_plus
repository_name: ajinkya446/ble_plus
publish_to: 'none'

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
