name: ble_plus_android_unused
description: Unused - see root package.
version: 1.0.4
repository: https://github.com/ajinkya446/ble_plus
repository_name: ajinkya446/ble_plus
publish_to: 'none'

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ble_plus_platform_interface:
    path: ../ble_plus_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
