name: ble_plus_android
description: Android implementation of the federated ble_plus platform package.
version: 1.0.5
homepage: https://github.com/ajinkya446/ble_plus
repository: https://github.com/ajinkya446/ble_plus
issue_tracker: https://github.com/ajinkya446/ble_plus/issues
repository_name: ajinkya446/ble_plus
publish_to: 'none'

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ble_plus_platform_interface:
    path: ../ble_plus_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ble_plus
        pluginClass: BlePlusPlugin
