name: ble_plus_workspace

packages:
  - packages/*

scripts:
  analyze:
    run: melos exec -c 1 -- flutter analyze
    description: Analyze all packages in the workspace.

  test:
    run: melos exec -c 1 -- flutter test
    description: Run unit tests across all packages.

  format:
    run: melos exec -c 1 -- dart format lib test
    description: Format Dart sources in each package.

  get:
    run: melos exec -c 1 -- flutter pub get
    description: Fetch dependencies for each package.
