name: ble_plus_platform_interface
description: "Platform interface package for ble_plus; shared types and platform contracts used by the plugin implementations across Android, iOS, macOS, Linux, Windows and Web."
version: 0.0.1


environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
